print ("Marinduque States College")
print ("Information Technology")
print ("Second Year, Section: F")
print ("Playing Basketball")
print ("Playing Volleyball")
print ("Playing Mobile and PC Games")
print ("Eating")
print ("Watching Movies")